package csd214.app.repositories;

import csd214.app.entities.BookEntity;
import csd214.app.entities.ProductEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DataJpaTest // Focuses exclusively on scanning Entities and Repositories [7]
public class ProductRepositoryTest {

    @Autowired
    private ProductRepository productRepository;

    @BeforeEach
    void setUp() {
        productRepository.deleteAll(); // Clean state
    }

    @Test
    void testSaveAndSearchByName() {
        BookEntity book1 = new BookEntity();
        book1.setTitle("The Hobbit");
        book1.setName("The Hobbit");
        book1.setPrice(15.99);

        BookEntity book2 = new BookEntity();
        book2.setTitle("The History of Rome");
        book2.setName("The History of Rome");
        book2.setPrice(25.00);

        productRepository.saveAll(Arrays.asList(book1, book2));

        assertNotNull(book1.getId());

        // Verify the dynamic SQL query generated by our derived method
        List<ProductEntity> foundItems = productRepository.findByNameContainingIgnoreCase("history");

        assertEquals(1, foundItems.size());
        assertEquals("The History of Rome", foundItems.get(0).getName());
    }
}
