package app.repositories;

import app.entities.GelPolishEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;


@DataJpaTest
class GelPolishRepositoryTest {

    @Autowired
    private GelPolishRepository polishRepository;

    @BeforeEach
    void setUp() {
        polishRepository.deleteAll(); // Clean state
    }

    @Test
    void testSaveAndSearchByColour() {
        GelPolishEntity polish1 = new GelPolishEntity();
        polish1.setColourShade("Pink");
        polish1.setTexture("Matte");
        polish1.setPrice(15.99);

        GelPolishEntity polish2 = new GelPolishEntity();
        polish2.setColourShade("Orange");
        polish2.setTexture("Shiny");
        polish2.setPrice(25.00);

        polishRepository.saveAll(Arrays.asList(polish1, polish2));

        assertNotNull(polish1.getId());

        // Verify the dynamic SQL query generated by our derived method
        List<GelPolishEntity> foundItems = polishRepository.findGelPolishEntitiesByColourShade("Pink");

        assertEquals(1, foundItems.size());
        assertEquals("Pink", foundItems.get(0).getColourShade());
    }
}