package app.repositories;
import app.entities.NailAccessoryEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DataJpaTest
class NailAccessoryRepositoryTest {

    @Autowired
    private NailAccessoryRepository accessoryRepository;

    @BeforeEach
    void setUp() {
        accessoryRepository.deleteAll(); // Clean state
    }

    @Test
    void testSaveAndSearchByAccessoryType() {
        NailAccessoryEntity accessory1 = new NailAccessoryEntity();
        accessory1.setAccessoryType("Drill");
        accessory1.setBrand("e.l.f");
        accessory1.setPrice(15.99);

        NailAccessoryEntity accessory2 = new NailAccessoryEntity();
        accessory2.setAccessoryType("File");
        accessory2.setBrand("nyx");
        accessory2.setPrice(5.00);

        accessoryRepository.saveAll(Arrays.asList(accessory1, accessory2));

        assertNotNull(accessory1.getId());

        // Verify the dynamic SQL query generated by our derived method
        List<NailAccessoryEntity> foundItems = accessoryRepository.findNailAccessoryEntitiesByAccessoryTypeIgnoreCase("Drill");

        assertEquals(1, foundItems.size());
        assertEquals("Drill", foundItems.get(0).getAccessoryType());
    }
}