package app.repositories;
import app.entities.NailKitEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DataJpaTest
class NailKitRepositoryTest {

    @Autowired
    private NailKitRepository kitRepository;

    @BeforeEach
    void setUp() {
        kitRepository.deleteAll(); // Clean state
    }

    @Test
    void testSaveAndSearchByKitLevel() {
        NailKitEntity kit1 = new NailKitEntity();
        kit1.setKitLevel("Beginner");
        kit1.setKitType("Nail Care");
        kit1.setPrice(35.99);

        NailKitEntity kit2 = new NailKitEntity();
        kit2.setKitLevel("Expert");
        kit2.setKitType("Acrylics");
        kit2.setPrice(500.00);

        kitRepository.saveAll(Arrays.asList(kit1, kit2));

        assertNotNull(kit1.getId());

        // Verify the dynamic SQL query generated by our derived method
        List<NailKitEntity> foundItems = kitRepository.findNailKitEntitiesByKitLevelIgnoreCase("Beginner");

        assertEquals(1, foundItems.size());
        assertEquals("Beginner", foundItems.get(0).getKitLevel());
    }
}